/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  /**
   * Original page router name.
   */
  static readonly ORIGIN_PAGE: string = 'OriginPage';

  /**
   * Full Screen Size.
   */
  static readonly FULL_SCREEN: string = '100%';

  /**
   * Web page router name.
   */
  static readonly WEB_PAGE: string = 'WebPage';

  /**
   * Original page router chinese name.
   */
  static readonly ORIGIN_PAGE_CHINESE: string = '原生页面';

  /**
   * Web page router chinese name.
   */
  static readonly WEB_PAGE_CHINESE: string = 'Web页面';

  /**
   * Original web page link.
   */
  static readonly ORIGIN_WEB_PAGE_LINK: string = 'resource://rawfile/index.html';

  /**
   * Original web page link.
   */
  static readonly WEB_PAGE_ADDRESS: string = 'resource://rawfile/index1.html';
}